#!/bin/bash

docker run \
	--env APPDYNAMICS_CONTROLLER_HOST_NAME=$APPD_CONTROLLER \
	--env APPDYNAMICS_AGENT_ACCOUNT_NAME=$APPD_ACCOUNT_NAME \
	--env APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=$APPD_ACCOUNT_KEY \
	--env APPDYNAMICS_CONTROLLER_PORT="443" \
	--env APPDYNAMICS_CONTROLLER_SSL_ENABLED="true" \
	--env APPDYNAMICS_AGENT_CREATE_NODE_IF_ABSENT="true" \
	--env APPDYNAMICS_HTTP_LISTENER="true" \
	--env APPDYNAMICS_HTTP_LISTENER_PORT="8090" \
	--env APPDYNAMICS_AGENT_HIERARCHY_PATH="HTTP_TEST|Machine1" \
	--env APPDYNAMICS_AGENT_APPLICATION_NAME="HTTP_TEST" \
	--env APPDYNAMICS_AGENT_NODE_NAME="HTTP_TEST" \
	--env APPDYNAMICS_AGENT_TIER_NAME="HTTP_TEST" \
	--env APPDYNAMICS_AGENT_UNIQUE_HOST_ID="EXTENSION_AGENT_1" \
	--env APPDYNAMICS_AGENT_MAX_METRICS="10000" \
	--env APPDYNAMICS_AGENT_LOG_DIR="/opt/appd/machine_agent/logs" \
	--env APPDYNAMICS_DEBUG_LEVEL="debug" \
	-p 8090:8090 \
	-d lhintzsc/machine-agent:latest 



